
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 21;
  public static final int LTEQ = 16;
  public static final int LPAREN = 23;
  public static final int PRIVATE = 4;
  public static final int MINUS = 10;
  public static final int DIFBECOMES = 7;
  public static final int STATIC = 40;
  public static final int INSTANCEOF = 3;
  public static final int RPAREN = 24;
  public static final int NOT = 18;
  public static final int SEMICOLON = 27;
  public static final int AND = 12;
  public static final int LT = 13;
  public static final int RT = 14;
  public static final int COMMA = 20;
  public static final int CLASS = 37;
  public static final int PLUS = 9;
  public static final int MAIN = 42;
  public static final int IF = 33;
  public static final int THIS = 45;
  public static final int DOT = 19;
  public static final int EOF = 0;
  public static final int RETURN = 36;
  public static final int RBRACKET = 22;
  public static final int TRUE = 43;
  public static final int NEW = 47;
  public static final int SUPER = 8;
  public static final int error = 1;
  public static final int BECOMESBECOMES = 6;
  public static final int BECOMES = 17;
  public static final int RTEQ = 15;
  public static final int VOID = 41;
  public static final int INTEGER_TYPE = 31;
  public static final int TIMES = 11;
  public static final int LBRACE = 25;
  public static final int ELSE = 34;
  public static final int SYSTEM_OUT_PRINTLN = 2;
  public static final int PROTECTED = 5;
  public static final int WHILE = 35;
  public static final int PUBLIC = 39;
  public static final int RBRACE = 26;
  public static final int EXTENDS = 38;
  public static final int STRING = 32;
  public static final int FALSE = 44;
  public static final int LENGTH = 46;
  public static final int INTEGER_LITERAL = 29;
  public static final int BOOLEAN_TYPE = 30;
  public static final int IDENTIFIER = 28;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SYSTEM_OUT_PRINTLN",
  "INSTANCEOF",
  "PRIVATE",
  "PROTECTED",
  "BECOMESBECOMES",
  "DIFBECOMES",
  "SUPER",
  "PLUS",
  "MINUS",
  "TIMES",
  "AND",
  "LT",
  "RT",
  "RTEQ",
  "LTEQ",
  "BECOMES",
  "NOT",
  "DOT",
  "COMMA",
  "LBRACKET",
  "RBRACKET",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "SEMICOLON",
  "IDENTIFIER",
  "INTEGER_LITERAL",
  "BOOLEAN_TYPE",
  "INTEGER_TYPE",
  "STRING",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "CLASS",
  "EXTENDS",
  "PUBLIC",
  "STATIC",
  "VOID",
  "MAIN",
  "TRUE",
  "FALSE",
  "THIS",
  "LENGTH",
  "NEW"
  };
}

