//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Apr 22 17:55:34 BRT 2017
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 23;
  public static final int LTEQ = 18;
  public static final int LPAREN = 25;
  public static final int PRIVATE = 6;
  public static final int MINUS = 12;
  public static final int DIFBECOMES = 9;
  public static final int STATIC = 42;
  public static final int INSTANCEOF = 5;
  public static final int RPAREN = 26;
  public static final int NOT = 20;
  public static final int SEMICOLON = 29;
  public static final int AND = 14;
  public static final int LT = 15;
  public static final int RT = 16;
  public static final int COMMA = 22;
  public static final int CLASS = 39;
  public static final int PLUS = 11;
  public static final int MAIN = 44;
  public static final int IF = 35;
  public static final int THIS = 47;
  public static final int DOT = 21;
  public static final int EOF = 0;
  public static final int RETURN = 38;
  public static final int RBRACKET = 24;
  public static final int TRUE = 45;
  public static final int NEW = 49;
  public static final int SUPER = 10;
  public static final int error = 1;
  public static final int BECOMESBECOMES = 8;
  public static final int BECOMES = 19;
  public static final int RTEQ = 17;
  public static final int VOID = 43;
  public static final int INTEGER_TYPE = 33;
  public static final int DOUBLE_TYPE = 3;
  public static final int TIMES = 13;
  public static final int ELSE = 36;
  public static final int LBRACE = 27;
  public static final int SYSTEM_OUT_PRINTLN = 2;
  public static final int PROTECTED = 7;
  public static final int WHILE = 37;
  public static final int PUBLIC = 41;
  public static final int RBRACE = 28;
  public static final int EXTENDS = 40;
  public static final int STRING = 34;
  public static final int FALSE = 46;
  public static final int FLOAT_TYPE = 4;
  public static final int LENGTH = 48;
  public static final int INTEGER_LITERAL = 31;
  public static final int BOOLEAN_TYPE = 32;
  public static final int IDENTIFIER = 30;
}

